/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      keyframes: {
        "olas-scroll": {
          "0%": { backgroundPosition: "100% " },
          "100%": { backgroundPosition: "0% " },
        },
        "cloud-float": {
          "0%": { transform: "translateX(-120%)" },
          "100%": { transform: "translateX(120vw)" },
        },
        "cloud-float-reverse": {
          "0%": { transform: "translateX(120vw)" },
          "100%": { transform: "translateX(-120%)" },
        },
        "bunting-sway": {
          "0%, 100%": { transform: "rotate(-2deg)" },
          "50%": { transform: "rotate(2deg)" },
        },
        "wave-drift": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "float-gentle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      animation: {
        "olas-scroll": "olas-scroll 4000s linear infinite",
        "cloud-float": "cloud-float 60s linear infinite",
        "cloud-float-reverse": "cloud-float-reverse 80s linear infinite",
        "bunting-sway": "bunting-sway 3s ease-in-out infinite",
        "wave-drift": "wave-drift 8s linear infinite",
        "float-gentle": "float-gentle 4s ease-in-out infinite",
      },
      fontFamily: {
        'space-mono': ['"Space Mono"', 'monospace'],
      },
      colors: {
        primaryLanding: "#FF7430",
        secondaryLanding: "#232323",
        CTALanding: "#F7F7F7",
        successLanding: "#14D455",
        errorLanding: "#E55010",
        linkLanding: "#3366CC",
        grayColor: "#757575",
        primaryHackeps: "#54311A",
        textPrimaryHackeps: "#F5F5F5",
        primaryHackepsDark: "#2F7D5F",
        secondaryHackeps: "#F5E7DE",
        textSecondaryHackeps: "#000000",
        blackHackeps: "#0F0F0F",
        lightHackeps: "#F5F5F5",
        grayLightHackeps: "#bbb8b8",
        grayLightHackepsDark: "#8c8787",
        grayStrongHackeps: "#444343",
        loginPage: "#77b1c9",
        successGreen: "#4caf50",
        blueSea: "#77b1c9",
        errorRed: "#f44336",
        blueSky: "#bdfffe",
        secondaryColorButton: "#237090",
        /* 10th Anniversary theme colors */
        skyTop: "#87CEEB",
        skyBottom: "#B0E0E6",
        skyMid: "#A8D8EA",
        bannerOrange: "#F28C28",
        hackepsOrange: "#F97316",
        seaDeep: "#5B9BD5",
        seaLight: "#87CEEB",
        sandBeige: "#F5E6D3",
        skyDay: "#94cbf5",
        nightNavy: "#2c465e",
        nightNavyDeep: "#15202b",
        headingInk: "#1a3a52",
      },
      screens: {
        sm: "576px",
        md: "768px",
        "max-md": { max: "768px" },
        "max-lg": { max: "998px" },
        "max-ml": { max: "1170px" },
        "max-xl": { max: "1400px" },
      },
      height: {
        128: "37rem",
        94: "25rem",
      },
    },
    backgroundImage: {
      "background-hero": "url('/src/imgs/hackers_group.jpg')",
      "background-patron": "url('/src/imgs/patron_imagen.png')",
      "background-none": "url()",
      "background-cartellA": "url('/src/assets/Cartell A.png')",
      "background-cartellB": "url('/src/assets/Cartell B.png')",
      "background-cartellC": "url('/src/assets/Cartell C.png')",
      "background-cartellD": "url('/src/assets/Cartell D.png')",
      'background-garabato': "url('/src/assets/img/garabato.png')",
    },
  },
  plugins: [],
};
